# Generated by Django 5.2.3 on 2025-06-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_image/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='recipe_image/')),
            ],
        ),
    ]
