# Generated by Django 5.2.3 on 2025-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Release_Date', models.DateField()),
                ('Genre', models.CharField(choices=[('AC', 'Action'), ('DR', 'Drama'), ('CO', 'Comedy'), ('HO', 'Horror'), ('RO', 'Romance'), ('SF', 'Science Fiction'), ('FA', 'Fantasy'), ('DO', 'Documentary'), ('TH', 'Thriller')], default='AC', max_length=20)),
                ('Description', models.TextField()),
                ('Poster', models.ImageField(blank=True, null=True, upload_to='movie_poster/')),
            ],
        ),
    ]
